spring:
  application:
    name: fitness-tracker-api
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: validate
logging:
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      file-name-pattern: "logs/archived/app.%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 1GB
      clean-history-on-start: false
  pattern:
     file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
     console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.dirijable.labs.lms.aop: DEBUG
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /swagger/openapi.yaml
  api-docs:
    path: /v3/api-docs
jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}
server:
  port: 8080
  servlet:
    context-path: /