--changeset dirijable:1
ALTER TABLE category ALTER COLUMN name TYPE VARCHAR(64);

ALTER TABLE instructor ALTER COLUMN first_name TYPE VARCHAR(64);
ALTER TABLE instructor ALTER COLUMN last_name TYPE VARCHAR(64);
ALTER TABLE instructor ALTER COLUMN specialization TYPE VARCHAR(128);

ALTER TABLE instructor ALTER COLUMN description TYPE VARCHAR(512);

ALTER TABLE course ALTER COLUMN name TYPE VARCHAR(64);
ALTER TABLE course ALTER COLUMN description TYPE VARCHAR(512);

ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(64);
ALTER TABLE users ALTER COLUMN password TYPE VARCHAR(64);
ALTER TABLE users ALTER COLUMN first_name TYPE VARCHAR(64);
ALTER TABLE users ALTER COLUMN last_name TYPE VARCHAR(64);

ALTER TABLE lesson ALTER COLUMN title TYPE VARCHAR(128);
ALTER TABLE lesson ALTER COLUMN content TYPE VARCHAR(128);

ALTER TABLE refresh_token ALTER COLUMN token TYPE VARCHAR(128);
ALTER TABLE refresh_token ALTER COLUMN user_email TYPE VARCHAR(64);

--rollback ALTER TABLE category ALTER COLUMN name TYPE TEXT;
--rollback ALTER TABLE instructor ALTER COLUMN first_name TYPE TEXT, ALTER COLUMN last_name TYPE TEXT, ALTER COLUMN specialization TYPE TEXT, ALTER COLUMN description TYPE TEXT;
--rollback ALTER TABLE course ALTER COLUMN name TYPE TEXT, ALTER COLUMN description TYPE TEXT;
--rollback ALTER TABLE users ALTER COLUMN email TYPE TEXT, ALTER COLUMN password TYPE TEXT, ALTER COLUMN first_name TYPE TEXT, ALTER COLUMN last_name TYPE TEXT;
--rollback ALTER TABLE lesson ALTER COLUMN title TYPE TEXT, ALTER COLUMN content TYPE TEXT;
--rollback ALTER TABLE refresh_token ALTER COLUMN token TYPE TEXT, ALTER COLUMN user_email TYPE TEXT;
